default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store(
      track: 'alpha',
      release_status: 'completed',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end

  desc "Deploy to internal testing track"
  lane :internal do
    upload_to_play_store(
      track: 'internal',
      release_status: 'completed',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end

  desc "Deploy to alpha track"
  lane :alpha do
    upload_to_play_store(
      track: 'alpha',
      release_status: 'completed',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end

  desc "Deploy to production track"
  lane :production do
    upload_to_play_store(
      track: 'production',
      release_status: 'completed',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end
end